<project>
    <parent>
        <groupId>com.novocib</groupId>
        <artifactId>novocib-backoffice</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>backoffice-app</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.novocib</groupId>
            <artifactId>module-stocks</artifactId>
        </dependency>
        <dependency>
            <groupId>com.novocib</groupId>
            <artifactId>module-timetracking</artifactId>
        </dependency>
    </dependencies>
</project>