<project>
    <parent>
        <groupId>com.novocib</groupId>
        <artifactId>novocib-backoffice</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>module-timetracking</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
    </dependencies>
</project>